esphome:
  name: "ir-blaster"
  friendly_name: ir-blaster

bk72xx:
  board: cb3s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LUGNKj3jrR2hep4E6nCLrDYlHvuDSdSjaWteFuDjhkE="
  actions:
    - action: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
#            carrier_frequency: 38kHz
            code: !lambda 'return command;'
            
ota:
  - platform: esphome
    password: "e23744c0fa02872fce76ec5cb82692af"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "IR Blaster Fallback Hotspot"
    password: "IRBlaster"

captive_portal:

light:
  - platform: status_led
    name: "Status"
    pin: P8

remote_transmitter:
  pin: P26
  carrier_duty_percent: 50%

# Receiver allows the original remote to be used and HA to follow along
remote_receiver:
  id: rcvr
  pin:
    number: P7
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 55%
#  filter: 10us
#  idle: 25ms
  dump: raw
  
climate:
  - platform: gree # whirlpool # coolix # midea_ir
    name: "Living Room AC"  
    model: yac1fb9 # yac # generic
