esphome:
  name: camera
  friendly_name: Camera
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

esp32:
  #board: seeed_xiao_esp32s3
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MiCyqtOdWKXDsBzFX7fRyYCVX+Km96qUOZlcGJ6E4K8="

ota:
  - platform: esphome
    password: "3b25b360253129cf06fc3d95537a3ef9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XIAO-ESP32S3 Fallback Hotspot"
    password: "fallbackpass"

captive_portal:

# Web server (to preview the camera stream)
web_server:
  port: 80

esp32_camera:
  #name: XIAO Camera
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13

  # Image settings
  name: Camera 1
  # ...

  #reset_pin: GPIO1
  #power_down_pin: GPIO2
  resolution: 640x480
  jpeg_quality: 10
  max_framerate: 10 fps
  idle_framerate: 0.2 fps
  #vertical_flip: true
  #horizontal_mirror: true

# Configuration for the status LED light
light:
  - platform: status_led
    id: light0
    name: "Voice Assistant State"
    pin:
      number: GPIO21
      inverted: true

# Configuration for I2S audio
i2s_audio:
  i2s_lrclk_pin: GPIO46 # Note: labeled as "useless"
  i2s_bclk_pin: GPIO42

# Configuration for the microphone using I2S audio
microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO41
    adc_type: external
    pdm: true

# Configuration for the Voice Assistant
voice_assistant:
  microphone: echo_microphone

# Configuration for the binary sensor (Boot Switch)
binary_sensor:    
  - platform: gpio
    pin: 
      number: GPIO2
      mode:
        input: true
        pullup: true
    name: Boot Switch
    internal: true
    on_press:
      - voice_assistant.start:
      - light.turn_off: light0
    on_release:
      - voice_assistant.stop:
      - light.turn_on: light0

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 60s

  - platform: template
    name: "Free Heap Memory"
    lambda: |-
      return (float)ESP.getFreeHeap() / 1024.0;
    unit_of_measurement: "kB"
    accuracy_decimals: 1
    update_interval: 60s

text_sensor:
  - platform: version
    name: "ESPHome Version"

button:
  - platform: restart
    name: "Restart ESP"

